export const GET_CATEGORIES = 'GET_CATEGORIES' // getCategories
export const GET_CATEGORY_POSTS = 'GET_CATEGORY_POSTS' // getCategoryPosts
export const GET_POSTS = 'GET_POSTS' // getPosts
export const GET_POST = 'GET_POST' // getPost
export const ADD_POST = 'ADD_POST' // addPost
export const UP_VOTE_POST = 'UP_VOTE_POST'
export const DOWN_VOTE_POST = 'DOWN_VOTE_POST'
export const EDIT_POST = 'EDIT_POST' // editPost
export const DELETE_POST = 'DELETE_POST' // deletePost
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS' // getPostComments
export const ADD_COMMENT = 'ADD_COMMENT' // addComment
export const GET_COMMENT = 'GET_COMMENT' // getComment
export const VOTE_ON_COMMENT = 'VOTE_ON_COMMENT' // voteOnComment
export const EDIT_COMMENT = 'EDIT_COMMENT' // editComment
export const DELETE_COMMENT = 'DELETE_COMMENT' // deleteComment
